## The Problem 
We have a whole bunch of data which is information about various different banknotes. For each measurement on a banknote, it is either classified as a counterfeit or not counterfeit (authentic). 
We have four different input values for each of the data points (variance, skewness, curtosis and entropy) and we have a label (0 indicates "not counterfeit" and 1 indicates "counterfeit")

We want to use supervised learning to predict or model some function that can take these four values(variance, skewness, curtosis and entropy) as input and predict what the output would be.

### Getting the data

In [3]:
import numpy as np
import pandas as pd

banknotes = pd.read_csv("dataset/banknotes.csv")

In [4]:
banknotes.head()

   variance  skewness  curtosis  entropy  class
0  -0.89569   3.00250 -3.606700 -3.44570      1
1   3.47690  -0.15314  2.530000  2.44950      0
2   3.91020   6.06500 -2.453400 -0.68234      0
3   0.60731   3.95440 -4.772000 -4.48530      1
4   2.37180   7.49080  0.015989 -1.74140      0

In [5]:
banknotes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB

In [6]:
banknotes.iloc[:20]

    variance  skewness  curtosis  entropy  class
0   -0.89569   3.00250 -3.606700 -3.44570      1
1    3.47690  -0.15314  2.530000  2.44950      0
2    3.91020   6.06500 -2.453400 -0.68234      0
3    0.60731   3.95440 -4.772000 -4.48530      1
4    2.37180   7.49080  0.015989 -1.74140      0
5   -2.21530  11.96250  0.078538 -7.78530      0
6    3.94330   2.50170  1.521500  0.90300      0
7    3.93100   1.85410 -0.023425  1.23140      0
8    3.97190   1.03670  0.759730  1.00130      0
9    0.55298  -3.46190  1.704800  1.10080      1
10   0.26877   4.98700 -5.150800 -6.39130      1
11  -1.13060   1.84580 -1.357500 -1.38060      1
12   1.95720  -5.11530  8.612700 -1.42970      0
13   0.57060  -0.02480  1.242100 -0.56210      0
14  -1.18590  -1.25190  2.263500  0.77239      1
15   3.25850  -4.46140  3.802400 -0.15087      0
16   5.02970  -4.97040  3.502500 -0.23751      0
17   0.39012  -0.14279 -0.031994  0.35084      1
18  -0.23610   9.32210  2.130700 -4.37930      0
19   0.32230  -0.89808  8.088300  0.69222      0